### ISSUE TITLE
Chapter 02 - `isomorphism.svg` image is broken

### ISSUE THREAD

**Issue by scriptin** [abuseofnotation/category-theory-illustrated#19]
When I open it directly at <https://boris-marinov.github.io/category-theory-illustrated/02_category/isomorphism.svg>, I get the following error:

```
This page contains the following errors:
error on line 3 at column 33: xmlns:i: '&#38;#38;ns_ai;' is not a valid URI
Below is a rendering of the page up to the first error.
```

Looking at the contents:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:i="&amp;#38;#38;ns_ai;"
```

it probably should be `xmlns:i="&amp;#38;ns_ai;"`

**Comment by abuseofnotation** [comment]
Used to have a similar problem, but it seems to work now.

**Comment by scriptin** [comment]
No, still reproducible, even GitHub shows an error on preview:
https://github.com/abuseofnotation/category-theory-illustrated/blob/master/_chapters/02_category/isomorphism.svg

**Comment by abuseofnotation** [comment]
I doesn't show error on my machine, but I removed the property, anyway.
