### ISSUE TITLE
Illustrations for logical operators are hard to read

### ISSUE THREAD

**Issue by Kaligule** [abuseofnotation/category-theory-illustrated#20]
The symbols ∧ (AND), ∨(OR) and ¬(NOT) are very abstract. Using them in a diagram makes that diagram harder to understand intuitively. You sort of have to already know them to understand what is going on. Also more complicated diagrams require a lot of mental effort to parse, which is in stark contrast to the other chapters, where diagrams are elegant and intuitive.

I would like to suggest other symbols:

### NOT
Have a red? curly? zigzaging? ring around the elements. This would work great for composition and would be easy to read even in more complicated diagrams (like when illustrating the rules of de morgan).

### AND 
Have a rounded rectangle around the terms, signaling that they are connected and are now one term. A bit similar to a [cartouche in egytian hieroglyphs](https://en.wikipedia.org/wiki/Egyptian_hieroglyphs#Cartouche)

### OR
Have a rounded rectangle around the terms, but with a line separating the two terms.

# Example

To illustrate how easy these symbols would make visual parsing I have drawn a diagram of the de morgan rule:

x OR y = (NOT x) AND (NOT y)

![de morgan](https://user-images.githubusercontent.com/3586246/138570858-997bc457-a25c-46ec-bc0d-d7856bd03333.png)

(drawn in [paint](https://jspaint.app/), I am ashamed by myself)

**Comment by abuseofnotation** [comment]
Thought about this more, these diagrams are harder is probably because classical logic is harder to picture.

But the chapter on classical logic is just a detour, so I think that we are good.

There is a problem I see with some diagrams being too small, but will fix that one later.
