### ISSUE TITLE
Please may you make a libre license official?

### ISSUE THREAD

**Issue by throwaway1037** [abuseofnotation/category-theory-illustrated#21]
#7 was closed with no libre license officially added, and the permission given was extremely vague and ambiguous.
So as to avoid any legal trouble, please may you make the licensing official and add a libre license?

**Comment by boris-marinov** [comment]
You are right, shouldn't have closed #7, leaving this opened until I sort it out.

**Comment by throwaway1037** [comment]
Thank you! :)
Please may you consider releasing under the CC-BY-SA-4.0-Int-or-later license?

**Comment by abuseofnotation** [comment]
Added a CC license
