### ISSUE TITLE
Grammar: it's > its

### ISSUE THREAD

**Issue by majidaldo** [abuseofnotation/category-theory-illustrated#29]
Please review cases where it's should be it's. Example:
,,,
alter it’s state.
,,,

**Comment by boris-marinov** [comment]
Thanks

**Comment by abuseofnotation** [comment]
I think I corrected all instances of this mistake. There were so many. I don't understand how I didn't see them before.

**Comment by majidaldo** [comment]
> 

...reviewers can. :)
