### ISSUE TITLE
Image of is letter function - incorrect mappings

### ISSUE THREAD

**Issue by rprominski** [abuseofnotation/category-theory-illustrated#37]
In the picture of is letter function https://github.com/abuseofnotation/category-theory-illustrated/blob/master/_chapters/01_set/char_boolean.svg two mappings are incorrect:
'z' - points to false
'#' - points to true

Technically it is still correct function (by definition of function), but it returns incorrect results, which might be confusing.

**Comment by abuseofnotation** [comment]
Thanks, fixed.
