### ISSUE TITLE
About ePub format output

### ISSUE THREAD

**Issue by incetarik** [abuseofnotation/category-theory-illustrated#45]
Hello!

First of all, I'd like to thank all the contributors for their contributions to this project.
I find it useful and I believe, such resources like this should be available in different formats as well.
I have seen that it is also possible to have a PDF format of the website, but `ePub` format is better than this as
it has better compatibility with book applications and you may have more tools (for note taking, highlighting, section and whatnot) compared to PDF, even though most of these are also available for PDF.

So this issue I open is about the possibility of whether the `epub` could also be provided maybe in releases section of this repository or on the website.

Thank you in advance.

**Comment by abuseofnotation** [comment]
This is an HTML version:

https://abuseofnotation.github.io/category-theory-illustrated/print/

Should be possible to convert it to epub with pandoc or similar software.

**Comment by incetarik** [comment]
@abuseofnotation thank you for your response and I agree that that is an HTML version indeed. But printing leads to save it in pdf format, what I asked was maybe with a software or automation, this repository would have a `Release` of an ePub output, possibly, also in other formats such as Pdf.

**Comment by abuseofnotation** [comment]
I am not saying that epub is not needed, I am just saying how it can potentially be made to work..
I just saved the above webpage locally (with browser "Save As") and ran: 

"pandoc -f html -t epub3 -o output.epub book.html"

This got me an epub version, but it has some problems with the formulas and also the way it separates the pages is illogical:

![image](https://github.com/abuseofnotation/category-theory-illustrated/assets/4872512/37603cf2-c2df-4b5a-a7d1-22e1ca6e1b98)

If someone knows how to fix these issues with the epub I will include it.

**Comment by abuseofnotation** [comment]
I generated an epub version using pandoc

https://github.com/abuseofnotation/category-theory-illustrated/blob/master/book.epub

It needs a bit of work, so I won't put it in the website.

**Comment by abuseofnotation** [comment]
Actually, I decided to remove the file for now. I like to keep the epub version for when I release the book in public, anyone who wants to get the epub for testing purposes can message me...
