### ISSUE TITLE
Error in sentence

### ISSUE THREAD

**Issue by cap-ricci** [abuseofnotation/category-theory-illustrated#60]
Hello, I believe there is an error in the Question at the end of Section "Isomorphisms Between Singleton Sets": 

`Try to come up with a good example that shows how a statement that demonstrates the isomorphism between singleton sets` 

should be 

`Try to come up with a good example that demonstrates the isomorphism between singleton sets` or something similar?

**Comment by abuseofnotation** [comment]
Fixed, thanks
