### ISSUE TITLE
Couple of typos

### ISSUE THREAD

**Issue by drshade** [abuseofnotation/category-theory-illustrated#64]
Just a bunch of notes I kept while reading through up until the end of chapter 1. All very minor, but some broke my flow - OCD is a curse! 

Great read so far thank you, and I hope you find these useful: 

# Introduction

I'm not sure I fully understand the quote on the first page - it reads strangely to me:

> "Well, I am told it does have its applications is programming language theory..."

Suggestion: Should `is` rather be `in`?

# Chapter 1 - Sets

> "Even most mathematical theories [...]"

Suggestion: Drop the `Even` at the start?

> "Theories that are like that are called abstract theories."

Suggestion: `Theories like _these_ are called abstract theories`

> "But theories have core concepts that don’t refer to anything in particular, but are instead left for people to generalize on."

Two usages of _but_ in the same sentence. I also do not fully understand what the sentence is trying to communicate.

Suggestion: "_Abstract_ theories have core concepts that don't refer to anything in particular, but are rather left for people to generalize upon." (Tying back to the "abstraction" introduced prior)

Alternatively - the following paragraphs do a great job of explaining this better and potentially the above sentence could be removed.

> "All numbers from the target have (or should have) two arrows pointing at them (one for the positive square root and one for the negative one), and that is OK."

Suggestion: "All numbers _in_ the target [...]"

> "Most of the types of programming are composite types — they are a combination of the primitive ones that are listed here. Again, we will cover these later."

Suggestion: "Most of the types _in_ programming [...]"

> "A peculiarity in such languages is that they don’t support [...]"

Suggestion: "A peculiarity _of_ such languages [...]"

> "We haven’t talked about isomorphisms yet, but this is what we will be doing till the end of this chapter."

Suggestion: "We haven’t talked about isomorphisms yet, but this is what we will be doing _for the rest_ of this chapter."

> "<!- [...] ->"

(Some dangling HTML comments being rendered just before the Addendum)

> "For these reasons, I think that currently, programmers are losing out by not utilizing the principles of functional composition."

Suggestion: Difficult to read (maybe remove the "I think that currently" bit?)

**Comment by abuseofnotation** [comment]
A curse and a blessing -- all of those are spot on, fixed them, keep it coming :)
